spring:
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mariadb://mariadb:3306/hello_docker
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
#
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  loggin:
#    level:
#      org.hibernate.SQL: debug
#      org.hibernate.type: tracer
